# -*- coding: utf-8 -*-
"""
Django settings for clean project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

try:
  from local_settings import *
except ImportError:
  pass