# -*- coding: utf-8 -*-
"""
Django settings for clean project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'clientes',
    'medicao',
<<<<<<< HEAD

=======
    'clean',
>>>>>>> 3eb5c9589ba56e20d735f6adc86b366de4d60d54
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin/'

try:
  from local_settings import *
except ImportError:
  pass